version: '3.7'

services:
  kocdigitalproducer:
    container_name: producer
    build:
      context: .
      dockerfile: DockerfileProducer
networks:
  elk:
    driver: bridge
  rabbitmq_go_net:
    driver: bridge

volumes:
  elasticsearch: